-- init.sql

DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
    id SERIAL PRIMARY KEY,          
    title VARCHAR(255) NOT NULL,     
    genre VARCHAR(100) NOT NULL,     
    poster TEXT NOT NULL,            
    year INTEGER NOT NULL,           
    rating REAL NOT NULL             
);

INSERT INTO movies (title, genre, poster, year, rating) VALUES 
('Breaking Bad', 'Drama', 'https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2008, 9.5),
('Stranger Things', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGJlZTM0YjM3MWVkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 2016, 8.7),
('Better Call Saul', 'Drama', 'https://m.media-amazon.com/images/M/MV5BZDA4YmE0OTYtMmRmNS00Mzk2LTlhM2MtN2I3MTUxYWJlN2EzXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2015, 8.9),
('The Last of Us', 'Drama', 'https://m.media-amazon.com/images/M/MV5BZGUzYTI3M2EtZmM0Yy00NGUyLWI4ODEtN2Q3ZGJlMTVsNzdkXkEyXkFqcGdeQXVyMjkwOTAyMDU._V1_.jpg', 2023, 8.8),
('Succession', 'Drama', 'https://m.media-amazon.com/images/M/MV5BZWU3NGRkZWEtM2Q1YS00MjYwLWIyY2UtZmY4NmI1OTI1NTA4XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2018, 8.9),
('The Bear', 'Comedy', 'https://m.media-amazon.com/images/M/MV5BZjE3YjVlZTUtZmI0Ni00NGRkLWE1OTItYTM0Mzk2OTNhYmFmXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg', 2022, 8.6),
('The Boys', 'Action', 'https://m.media-amazon.com/images/M/MV5BZDA4YmE0OTYtMmRmNS00Mzk2LTlhM2MtN2I3MTUxYWJlN2EzXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2019, 8.7),
('Arcane', 'Animation', 'https://m.media-amazon.com/images/M/MV5BYmU1ZWMwZWYtMzNiMi00ZmE2LWE1N2UtNjQwMTQyZmU5NjY3XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2021, 9.0),
('Dark', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMmIwZjg1Y2ItNWQ5Yy00YzE1LWE0ZWMtY2NmMjIwYmYwNWZlXkEyXkFqcGdeQXVyNjM0MTI4Mw@@._V1_.jpg', 2017, 8.7),
('The Crown', 'History', 'https://m.media-amazon.com/images/M/MV5BZmY0MzAyNTgtMzY3OS00MDlhLWFmN2ItNWRiMjA1YmRkZTVmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 2016, 8.6),
('Sherlock', 'Mystery', 'https://m.media-amazon.com/images/M/MV5BMWY3NTljMjEtYzRiMi00NWM2LTkzNjItZTVmZjE0MTdjMjJhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2010, 9.1),
('Peaky Blinders', 'Crime', 'https://m.media-amazon.com/images/M/MV5BZjA0MTM4MTQtNzY5MC00NzY3LWI1ZTgtYzcxMjkyMzU4MDZiXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2013, 8.8),
('Fargo', 'Crime', 'https://m.media-amazon.com/images/M/MV5BN2ZmMjA0ZDYtMzQ1MS00ZTMwLWFjYmItYmExNmE3YjE3N2I0XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg', 2014, 8.9),
('Mindhunter', 'Thriller', 'https://m.media-amazon.com/images/M/MV5BNWNmYzQ1MzUtNmI5My00NDUyLWFjOWQtOTg3YzhjOTU3MzU4XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2017, 8.6),
('True Detective', 'Crime', 'https://m.media-amazon.com/images/M/MV5BNWNmYzQ1MzUtNmI5My00NDUyLWFjOWQtOTg3YzhjOTU3MzU4XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2014, 8.9),
('The Mandalorian', 'Action', 'https://m.media-amazon.com/images/M/MV5BN2M2YTAzMTItZDgyNy00MzE1LWEwZGItZjk2ZWZlYjA5ZjgxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2019, 8.7),
('House of the Dragon', 'Fantasy', 'https://m.media-amazon.com/images/M/MV5BZjUyN2VlZGEtNGEyZC00YjViLWI3OGEtZGZkY2YxMWRmYzBlXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2022, 8.4),
('Severance', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BOThjZTM4ZmUtZTFjOS00YjJmLTgzYjQtYzdmYjJlY2RjMDQ2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2022, 8.7),
('Cobra Kai', 'Action', 'https://m.media-amazon.com/images/M/MV5BMjA3NTY3MTQ2OF5BMl5BanBnXkFtZTgwNzYwMDM4NzM@._V1_.jpg', 2018, 8.5),
('The Witcher', 'Fantasy', 'https://m.media-amazon.com/images/M/MV5BMDEwOWVlY2EtMWI0ZC00OWVmLWJmZGItYTk3YjYzN2Y0YmFkXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg', 2019, 8.0),
('Mr. Robot', 'Drama', 'https://m.media-amazon.com/images/M/MV5BM2QyNDIzYmMtN2NlYS00ZjlmLWFlZDYtZGU1NzcyYTMxZjExXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2015, 8.5),
('Ted Lasso', 'Comedy', 'https://m.media-amazon.com/images/M/MV5BMTdmY2MzYmYtYzY5Mi00MzYxLWFlYWQtMGY1YTFmNjNlYjI5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2020, 8.8),
('Ozark', 'Crime', 'https://m.media-amazon.com/images/M/MV5BZTMxMGM5MjItNDI5Mi00YjE2LWFlZTMtNjTrM2M1NmFjOWE1XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2017, 8.5),
('Squid Game', 'Thriller', 'https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg', 2021, 8.0),
('Black Mirror', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BYTM3YWVhMDMtNjczMy00N2YyLWJlZDctYjdmNmI2MTExOTM1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 2011, 8.7),
('Narcos', 'Crime', 'https://m.media-amazon.com/images/M/MV5BNmFjODU3YzgtMGUwNC00ZGI3LWIyZDYtZDUyZGUxYmQ1MzcyXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2015, 8.8),
('Westworld', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMTRmYzY3NjQtZmE3Ny00MzVlLTlhZTYtN2YyYTc2ZmMzMmU5XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2016, 8.5),
('The Office', 'Comedy', 'https://m.media-amazon.com/images/M/MV5BMDNkOTE4NDQtMTNmYi00MWE0LWEzZTMtYzhjNzhhNjlhNTVjXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', 2005, 9.0),
('The Queen Gambit', 'Drama', 'https://m.media-amazon.com/images/M/MV5BM2EwMmRhMmUtMzBmMS00ZDQ3LTg4OGEtNjlkODk3ZTMxMmJlXkEyXkFqcGdeQXVyMjkwOTAyMDU._V1_.jpg', 2020, 8.6),
('Euphoria', 'Drama', 'https://m.media-amazon.com/images/M/MV5BMjA3NTY3MTQ2OF5BMl5BanBnXkFtZTgwNzYwMDM4NzM@._V1_.jpg', 2019, 8.3),
('Yellowstone', 'Western', 'https://m.media-amazon.com/images/M/MV5BZmY0MzAyNTgtMzY3OS00MDlhLWFmN2ItNWRiMjA1YmRkZTVmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 2018, 8.7),
('The Sandman', 'Fantasy', 'https://m.media-amazon.com/images/M/MV5BTI0MDY0YmUtMDhjNS00ZTIyLTgxOGYtZGVlOTllYmI5NTEzXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg', 2022, 7.7),
('Chernobyl', 'History', 'https://m.media-amazon.com/images/M/MV5BZGQ2YTMxZmEtYjdlOC00N2EwLTkzNWQtZWFhMWY3N2ExYmI2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2019, 9.4),
('Vikingos', 'History', 'https://m.media-amazon.com/images/M/MV5BODk4OTU0NjUtYjA0Ni00Y2M3LWI1NWMtOTdlNDc5OTYxM2Y3XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2013, 8.5),
('The Umbrella Academy', 'Action', 'https://m.media-amazon.com/images/M/MV5BMjA3NTY3MTQ2OF5BMl5BanBnXkFtZTgwNzYwMDM4NzM@._V1_.jpg', 2019, 7.9),
('Hannibal', 'Thriller', 'https://m.media-amazon.com/images/M/MV5BM2EwMmRhMmUtMzBmMS00ZDQ3LTg4OGEtNjlkODk3ZTMxMmJlXkEyXkFqcGdeQXVyMjkwOTAyMDU._V1_.jpg', 2013, 8.5),
('Brooklyn Nine-Nine', 'Comedy', 'https://m.media-amazon.com/images/M/MV5BNzVkYWY4NzYtMWFlZi00YzkwLThhZDItZjcxYTU4ZTMzMDZmXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', 2013, 8.4),
('Bojack Horseman', 'Animation', 'https://m.media-amazon.com/images/M/MV5BYWTMOTNjY2YtY2E3ZC00NzViLTgzY2MtZTlmZjk2YzRjMjEzXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg', 2014, 8.8),
('Rick and Morty', 'Animation', 'https://m.media-amazon.com/images/M/MV5BZjRjOTFkOTktZWUzMi00YzMyLThkMmYtMjEwNmQyNzliYTNmXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_.jpg', 2013, 9.1),
('Invincible', 'Animation', 'https://m.media-amazon.com/images/M/MV5BMmIwZjg1Y2ItNWQ5Yy00YzE1LWE0ZWMtY2NmMjIwYmYwNWZlXkEyXkFqcGdeQXVyNjM0MTI4Mw@@._V1_.jpg', 2021, 8.7),
('The White Lotus', 'Comedy', 'https://m.media-amazon.com/images/M/MV5BMjA3NTY3MTQ2OF5BMl5BanBnXkFtZTgwNzYwMDM4NzM@._V1_.jpg', 2021, 7.9),
('Barry', 'Comedy', 'https://m.media-amazon.com/images/M/MV5BMTdmY2MzYmYtYzY5Mi00MzYxLWFlYWQtMGY1YTFmNjNlYjI5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2018, 8.4),
('Friends', 'Comedy', 'https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwNjItNWY4ZGU5NTNlZjA5XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg', 1994, 8.9),
('The Wire', 'Crime', 'https://m.media-amazon.com/images/M/MV5BNmFjODU3YzgtMGUwNC00ZGI3LWIyZDYtZDUyZGUxYmQ1MzcyXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2002, 9.3),
('The Sopranos', 'Crime', 'https://m.media-amazon.com/images/M/MV5BZGJjYzhjYTYtMDBjYy00OWU1LTg5OTYtNmYwOTZmZjE3ZDdhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 1999, 9.2),
('Lost', 'Adventure', 'https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGJlZTM0YjM3MWVkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 2004, 8.3),
('Money Heist', 'Crime', 'https://m.media-amazon.com/images/M/MV5BDIUxZDVhNGMtZGRhNC00M2I5LWEwZTAtZTJiN2ZlNWYxYWQ1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 2017, 8.2),
('Beef', 'Comedy', 'https://m.media-amazon.com/images/M/MV5BZmY0MzAyNTgtMzY3OS00MDlhLWFmN2ItNWRiMjA1YmRkZTVmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 2023, 8.0),
('Silo', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMTdmY2MzYmYtYzY5Mi00MzYxLWFlYWQtMGY1YTFmNjNlYjI5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2023, 8.1),
('Fallout', 'Sci-Fi', 'https://m.media-amazon.com/images/M/MV5BMTdmY2MzYmYtYzY5Mi00MzYxLWFlYWQtMGY1YTFmNjNlYjI5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg', 2024, 8.5);